#!/bin/bash
#  Bash Menu Script Example

PS3='Please enter your choice: '
options=("Start Jupyter-k3d Docker" "Stop Jupyter-k3d Container" "Restart Jupyter-k3d Container" "Remove Jupyter-k3d Container" \
    "Copy Container Dir K3D-jupyter Here" "Enter the Docker Container jupyter-k3d" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Start Jupyter-k3d Docker")
            echo "Open http://localhost:8888 wiyh your browser. "
            docker run -d --name jupyter-k3d -p 8888:8888 --user root -v $(pwd)/work:/home/jovyan/work jacknorthrup/jupyter-k3d:latest
            ;;        
        "Stop Jupyter-k3d Container")
            docker stop jupyter-k3d
            ;;
        "Restart Jupyter-k3d Container")
            docker start jupyter-k3d
            ;;            
        "Remove Jupyter-k3d Container")
            docker rm jupyter-k3d
            ;;
        "Copy Container Dir K3D-jupyter Here")
            sudo docker cp jupyter-k3d:/home/jovyan/K3D-jupyter/. .
            ;;            
        "Enter the Docker Container jupyter-k3d")
            docker exec -it jupyter-k3d bash
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done
# key-pem-csr-info.html
#pip install jupyter_nbextensions_configurator
#jupyter nbextensions_configurator enable         